import argparse
from pathlib import Path

import torch

from wllm_omni import DEFAULT_IMAGE, DEFAULT_MODEL, DEFAULT_NEGATIVE_PROMPT, DEFAULT_PROMPT, OmniLLM
from wllm_omni.engine.pipeline import AR_TEXT_PIPELINE, QWEN_TO_WAN_I2V_PIPELINE, WAN_I2V_PIPELINE


def parse_args():
    parser = argparse.ArgumentParser(description="Minimal Wan2.2 TI2V/I2V runner.")
    parser.add_argument("--model", default=DEFAULT_MODEL)
    parser.add_argument("--image", default=DEFAULT_IMAGE)
    parser.add_argument("--prompt", default=DEFAULT_PROMPT)
    parser.add_argument("--negative-prompt", default=DEFAULT_NEGATIVE_PROMPT)
    parser.add_argument("--preset", choices=["quality"], default="quality")
    parser.add_argument("--output", default="./download/example_wan22_i2v_quality.mp4")
    parser.add_argument("--seed", type=int, default=None)
    parser.add_argument("--disable-cpu-offload", action="store_true")
    parser.add_argument("--max-num-seqs", type=int, default=2)
    parser.add_argument("--profile", action="store_true", help="Print a per-request diffusion profiler summary.")
    parser.add_argument(
        "--vae-dtype",
        choices=["fp32", "bf16"],
        default="fp32",
        help="VAE load/decode dtype. fp32 is the stable default; bf16 can be profiled as an experimental speed policy.",
    )
    parser.add_argument(
        "--probe-condition-cache",
        action="store_true",
        help="Run an extra prepare_latents probe to check whether Wan condition tensors are seed-independent.",
    )
    parser.add_argument(
        "--mini-omni",
        action="store_true",
        help="Run the request through the configured mini-Omni pipeline runtime.",
    )
    parser.add_argument(
        "--pipeline",
        choices=[AR_TEXT_PIPELINE, WAN_I2V_PIPELINE, QWEN_TO_WAN_I2V_PIPELINE],
        default=None,
        help=(
            "Pipeline topology to execute. ar_text is a single AR stage; "
            "wan_i2v is a single diffusion stage; qwen_to_wan_i2v is AR prompt bridge -> Wan diffusion."
        ),
    )
    parser.add_argument(
        "--ar-model",
        default=None,
        help="Local CausalLM model path for the mini-Omni AR stage. Requires --mini-omni.",
    )
    parser.add_argument(
        "--ar-max-new-tokens",
        type=int,
        default=64,
        help="Maximum new tokens generated by the mini-Omni AR stage.",
    )
    return parser.parse_args()


def _parse_vae_dtype(value: str) -> torch.dtype:
    if value == "fp32":
        return torch.float32
    if value == "bf16":
        return torch.bfloat16
    raise ValueError(f"Unsupported VAE dtype: {value}")


def _format_elapsed_ms(elapsed_s) -> str:
    if elapsed_s is None:
        return "None"
    return f"{float(elapsed_s) * 1000.0:.2f}"


def _format_ms(value) -> str:
    if value is None:
        return "None"
    return f"{float(value):.2f}"


def _print_mini_omni_trace(trace) -> None:
    if trace is None:
        return
    stages = " -> ".join(stage.name for stage in trace.stages)
    graph_nodes = " -> ".join(getattr(trace, "graph_nodes", []) or [])
    pipeline = getattr(trace, "pipeline", None)
    print(f"[wllm-omni][mini-omni] request_id={trace.request_id} pipeline={pipeline} stages={stages}", flush=True)
    if graph_nodes:
        print(f"[wllm-omni][mini-omni] graph={graph_nodes}", flush=True)
    for stage in trace.stages:
        metadata = stage.metadata
        elapsed_text = _format_elapsed_ms(metadata.get("elapsed_s"))
        if stage.name == "ar.prompt_bridge":
            print(
                "[wllm-omni][mini-omni] "
                f"ar.model={metadata.get('model')} "
                f"ar.mode={metadata.get('mode')} "
                f"ar.input_tokens={metadata.get('input_tokens')} "
                f"ar.prefill_tokens={metadata.get('prefill_tokens')} "
                f"ar.output_tokens={metadata.get('output_tokens')} "
                f"ar.elapsed_ms={elapsed_text} "
                f"ar.prefill_ms={_format_elapsed_ms(metadata.get('prefill_elapsed_s'))} "
                f"ar.decode_ms={_format_elapsed_ms(metadata.get('decode_elapsed_s'))} "
                f"ar.ttft_ms={_format_elapsed_ms(metadata.get('ttft_s'))} "
                f"ar.decode_steps={metadata.get('decode_model_steps')} "
                f"ar.decode_step_mean_ms={_format_ms(metadata.get('decode_step_mean_ms'))} "
                f"ar.kv_cache={metadata.get('kv_cache_enabled')} "
                f"ar.kv_cache_type={metadata.get('kv_cache_type')}",
                flush=True,
            )
        elif stage.name == "diffusion.wan22_i2v":
            load_elapsed_text = _format_elapsed_ms(metadata.get("load_elapsed_s"))
            print(
                "[wllm-omni][mini-omni] "
                f"diffusion.bridge={metadata.get('bridge')} "
                f"diffusion.source_node={metadata.get('source_node')} "
                f"diffusion.source_request_id={metadata.get('source_request_id')} "
                f"diffusion.load_was_cold={metadata.get('load_was_cold')} "
                f"diffusion.load_ms={load_elapsed_text} "
                f"diffusion.elapsed_ms={elapsed_text}",
                flush=True,
            )


def main():
    args = parse_args()
    pipeline = args.pipeline
    enable_mini_omni = args.mini_omni or pipeline is not None
    if args.ar_model is not None and not enable_mini_omni:
        raise ValueError("--ar-model requires --mini-omni or a pipeline with an AR stage.")
    if args.ar_model is not None and pipeline == WAN_I2V_PIPELINE:
        raise ValueError("--ar-model is not used by --pipeline wan_i2v.")
    llm = OmniLLM(
        args.model,
        use_cpu_offload=not args.disable_cpu_offload,
        max_num_seqs=args.max_num_seqs,
        enable_profiling=args.profile,
        vae_dtype=_parse_vae_dtype(args.vae_dtype),
        probe_condition_cache=args.probe_condition_cache,
        enable_mini_omni=enable_mini_omni,
        pipeline=pipeline,
        ar_model=args.ar_model,
        ar_max_new_tokens=args.ar_max_new_tokens,
    )
    sampling_params = llm.preset(args.preset)
    if args.seed is not None:
        sampling_params.seed = args.seed
    if pipeline == AR_TEXT_PIPELINE:
        ar_output = llm.generate_ar(args.prompt)
        _print_mini_omni_trace(llm.last_omni_trace)
        print(ar_output.text)
        return
    generation = llm.generate(args.image, args.prompt, args.negative_prompt, sampling_params)
    output_path = Path(args.output)
    llm.save(output=generation, output_path=output_path)
    _print_mini_omni_trace(llm.last_omni_trace)
    print(output_path.resolve())
