import argparse
from pathlib import Path

import torch

from wllm_omni import DEFAULT_IMAGE, DEFAULT_MODEL, DEFAULT_NEGATIVE_PROMPT, DEFAULT_PROMPT, OmniLLM


def parse_args():
    parser = argparse.ArgumentParser(description="Minimal Wan2.2 TI2V/I2V runner.")
    parser.add_argument("--model", default=DEFAULT_MODEL)
    parser.add_argument("--image", default=DEFAULT_IMAGE)
    parser.add_argument("--prompt", default=DEFAULT_PROMPT)
    parser.add_argument("--negative-prompt", default=DEFAULT_NEGATIVE_PROMPT)
    parser.add_argument("--preset", choices=["quality"], default="quality")
    parser.add_argument("--output", default="./download/example_wan22_i2v_quality.mp4")
    parser.add_argument("--seed", type=int, default=None)
    parser.add_argument("--disable-cpu-offload", action="store_true")
    parser.add_argument("--max-num-seqs", type=int, default=2)
    parser.add_argument("--profile", action="store_true", help="Print a per-request diffusion profiler summary.")
    parser.add_argument(
        "--vae-dtype",
        choices=["fp32", "bf16"],
        default="fp32",
        help="VAE load/decode dtype. fp32 is the stable default; bf16 can be profiled as an experimental speed policy.",
    )
    parser.add_argument(
        "--probe-condition-cache",
        action="store_true",
        help="Run an extra prepare_latents probe to check whether Wan condition tensors are seed-independent.",
    )
    parser.add_argument(
        "--mini-omni",
        action="store_true",
        help="Run the request through the minimal AR -> diffusion Omni runtime.",
    )
    parser.add_argument(
        "--ar-model",
        default=None,
        help="Local CausalLM model path for the mini-Omni AR stage. Requires --mini-omni.",
    )
    parser.add_argument(
        "--ar-max-new-tokens",
        type=int,
        default=64,
        help="Maximum new tokens generated by the mini-Omni AR stage.",
    )
    parser.add_argument(
        "--ar-only",
        action="store_true",
        help="Run only the mini-Omni AR stage and print the generated text.",
    )
    return parser.parse_args()


def _parse_vae_dtype(value: str) -> torch.dtype:
    if value == "fp32":
        return torch.float32
    if value == "bf16":
        return torch.bfloat16
    raise ValueError(f"Unsupported VAE dtype: {value}")


def _print_mini_omni_trace(trace) -> None:
    if trace is None:
        return
    stages = " -> ".join(stage.name for stage in trace.stages)
    print(f"[wllm-omni][mini-omni] request_id={trace.request_id} stages={stages}", flush=True)
    for stage in trace.stages:
        if stage.name != "ar.prompt_bridge":
            continue
        metadata = stage.metadata
        elapsed_s = metadata.get("elapsed_s")
        elapsed_ms = None if elapsed_s is None else float(elapsed_s) * 1000.0
        elapsed_text = "None" if elapsed_ms is None else f"{elapsed_ms:.2f}"
        print(
            "[wllm-omni][mini-omni] "
            f"ar.model={metadata.get('model')} "
            f"ar.mode={metadata.get('mode')} "
            f"ar.input_tokens={metadata.get('input_tokens')} "
            f"ar.output_tokens={metadata.get('output_tokens')} "
            f"ar.elapsed_ms={elapsed_text}",
            flush=True,
        )


def main():
    args = parse_args()
    if args.ar_model is not None and not args.mini_omni:
        raise ValueError("--ar-model requires --mini-omni.")
    if args.ar_only and not args.mini_omni:
        raise ValueError("--ar-only requires --mini-omni.")
    llm = OmniLLM(
        args.model,
        use_cpu_offload=not args.disable_cpu_offload,
        max_num_seqs=args.max_num_seqs,
        enable_profiling=args.profile,
        vae_dtype=_parse_vae_dtype(args.vae_dtype),
        probe_condition_cache=args.probe_condition_cache,
        enable_mini_omni=args.mini_omni,
        ar_model=args.ar_model,
        ar_max_new_tokens=args.ar_max_new_tokens,
    )
    sampling_params = llm.preset(args.preset)
    if args.seed is not None:
        sampling_params.seed = args.seed
    if args.ar_only:
        ar_output = llm.generate_ar(args.prompt)
        _print_mini_omni_trace(llm.last_omni_trace)
        print(ar_output.text)
        return
    generation = llm.generate(args.image, args.prompt, args.negative_prompt, sampling_params)
    output_path = Path(args.output)
    llm.save(output=generation, output_path=output_path)
    _print_mini_omni_trace(llm.last_omni_trace)
    print(output_path.resolve())
